"""Rendering: coloured console summary and a plain-text incident report."""
from __future__ import annotations
import sys
from datetime import datetime, timezone
from typing import List

from models import Incident

_SEV_COLOR = {"critical": "\033[1;31m", "high": "\033[1;33m", "medium": "\033[0;33m", "low": "\033[0;36m"}
_RESET = "\033[0m"
_DIM = "\033[2m"
_BOLD = "\033[1m"


def _c(txt, code, color):
    return f"{code}{txt}{_RESET}" if color else txt


def console_summary(incidents: List[Incident], total_events: int, color: bool = True) -> None:
    real = [i for i in incidents if i.severity != "low" or i.score >= 15]
    print()
    print(_c("  INTRUDER — detection summary", _BOLD, color))
    print(f"  {total_events} events analyzed · {len(real)} incident(s) surfaced")
    print("  " + "-" * 64)
    if not real:
        print("  No incidents detected. Logs look clean (or the format wasn't recognized).")
        return
    for inc in real:
        col = _SEV_COLOR.get(inc.severity, "")
        head = f"  [{inc.id}] {inc.severity.upper():8} score {inc.score:<3} ({inc.confidence} confidence)"
        print(_c(head, col, color))
        tag = "external" if inc.external else "internal"
        print(f"        {inc.ip}  [{tag} · {inc.geo}]")
        if inc.chain:
            print(f"        {_c('chain:', _DIM, color)} " + " -> ".join(k["stage"] for k in inc.chain))
        if inc.techniques:
            print(f"        {_c('ATT&CK:', _DIM, color)} " + ", ".join(t.split(' · ')[0] for t in inc.techniques))
        print()


def text_report(inc: Incident) -> str:
    L: List[str] = []
    L.append(f"# INCIDENT REPORT — {inc.id}")
    L.append("")
    L.append(f"Severity        : {inc.severity.upper()}  (threat score {inc.score}, confidence {inc.confidence})")
    tag = "external" if inc.external else "internal"
    L.append(f"Source          : {inc.ip}  [{tag} · {inc.geo}]")
    L.append(f"Events observed : {inc.stats['total']}  ({inc.stats['fails']} failures, {inc.stats['scans']} scans)")
    if inc.techniques:
        L.append(f"MITRE ATT&CK    : {'; '.join(inc.techniques)}")
    L.append("")
    L.append("## Summary")
    L.append(inc.narrative)
    L.append("")
    if inc.chain:
        L.append("## Attack chain")
        for i, k in enumerate(inc.chain, 1):
            L.append(f"{i}. [{k['time']}] {k['stage']} — {k['desc']}")
        L.append("")
    L.append("## Recommended response")
    for i, a in enumerate(inc.actions, 1):
        L.append(f"{i}. {a}")
    L.append("")
    L.append("## Evidence (sample log lines)")
    for f in inc.findings:
        tech = f" [{f.technique}]" if f.technique and f.technique != "behavioral" else ""
        L.append(f"* {f.title}{tech}")
        for e in f.evidence[:4]:
            L.append(f"    {e.line()}")
    L.append("")
    L.append(f"Generated by Intruder · {datetime.now(timezone.utc).isoformat()}")
    return "\n".join(L)
